services:
  db:
    image: postgres:15-alpine  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.docker
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env.docker  
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/www/html/static
      - media_volume:/var/www/html/media
      - certbot_data:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_data:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    depends_on:
      - nginx

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot_data:
  certbot_certs: