# Generated by Django 5.1.6 on 2025-04-03 12:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_alter_menu_options_menu_carbohydrates_menu_fats_and_more"),
        ("restaurant", "0003_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Тип бронирования"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание типа бронирования"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип бронирования",
                "verbose_name_plural": "Типы бронирования",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Название типа комнаты",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание типа комнаты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип комнаты",
                "verbose_name_plural": "Типы комнат",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название комнаты"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Вместимость (человек)",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Площадь (кв.м)",
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Стоимость аренды комнаты за час",
                        max_digits=10,
                        verbose_name="Цена за час",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание комнаты"
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True,
                        help_text="Перечислите особенности комнаты (проектор, звуковое оборудование и т.д.)",
                        null=True,
                        verbose_name="Особенности и удобства",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, если комната доступна для бронирования",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="restaurant.restaurant",
                        verbose_name="Ресторан",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms",
                        to="restaurant.section",
                        verbose_name="Секция",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms",
                        to="room.roomtype",
                        verbose_name="Тип комнаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комната для мероприятий",
                "verbose_name_plural": "Комнаты для мероприятий",
                "ordering": ["restaurant", "name"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название пакета"),
                ),
                ("description", models.TextField(verbose_name="Описание пакета")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Полная стоимость пакета (включая блюда)",
                        max_digits=10,
                        verbose_name="Стоимость пакета",
                    ),
                ),
                (
                    "min_guests",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Минимальное количество гостей"
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        verbose_name="Максимальное количество гостей"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, если пакет доступен для бронирования",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "booking_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="room.bookingtype",
                        verbose_name="Тип мероприятия",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="room.room",
                        verbose_name="Комната",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пакет услуг",
                "verbose_name_plural": "Пакеты услуг",
                "ordering": ["room", "name"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=255, verbose_name="Имя клиента"),
                ),
                (
                    "client_phone",
                    models.CharField(max_length=20, verbose_name="Телефон клиента"),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email клиента",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата мероприятия")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "guests_count",
                    models.PositiveIntegerField(verbose_name="Количество гостей"),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True, null=True, verbose_name="Особые пожелания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("completed", "Завершено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус бронирования",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Полная стоимость бронирования",
                        max_digits=10,
                        verbose_name="Общая стоимость",
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Внесенная предоплата",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "booking_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="room.bookingtype",
                        verbose_name="Тип мероприятия",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="room.package",
                        verbose_name="Выбранный пакет",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="room.room",
                        verbose_name="Комната",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="rooms/images/", verbose_name="Фотография"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если это главное фото комнаты",
                        verbose_name="Главное фото",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="room.room",
                        verbose_name="Комната",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография комнаты",
                "verbose_name_plural": "Фотографии комнат",
                "ordering": ["-is_main", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Примечания"
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_menus",
                        to="products.menu",
                        verbose_name="Блюдо",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="room.package",
                        verbose_name="Пакет услуг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блюдо в пакете",
                "verbose_name_plural": "Блюда в пакете",
                "ordering": ["package", "menu_item__name_ru"],
                "unique_together": {("package", "menu_item")},
            },
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["room", "booking_type"], name="room_packag_room_id_962099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["is_active"], name="room_packag_is_acti_7d018e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["room", "date"], name="room_bookin_room_id_30e28c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="room_bookin_status_9466a2_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["restaurant", "name"], name="room_room_restaur_10dde9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["is_active"], name="room_room_is_acti_de728b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("restaurant", "name")},
        ),
    ]
