# Generated by Django 5.1.7 on 2025-04-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(null=True, verbose_name="Позиция"),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Город",
            },
        ),
    ]
