# Generated by Django 5.1.6 on 2025-03-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Город", "verbose_name_plural": "Город"},
        ),
    ]
