# Generated by Django 5.1.6 on 2025-04-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0002_alter_city_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название ресторана"),
                ),
                (
                    "iiko_organization_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID организации из iiko Cloud API",
                    ),
                ),
                (
                    "external_menu_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Внешний ID меню из iiko Cloud API",
                    ),
                ),
                (
                    "price_category_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID ценной категории из iiko Cloud API",
                    ),
                ),
                (
                    "department_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID подразделения из iiko Waiter",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurants",
                        to="cities.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
                "indexes": [
                    models.Index(fields=["name"], name="restaurant__name_cf5999_idx")
                ],
            },
        ),
    ]
