# Generated by Django 5.1.6 on 2025-04-02 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_restaurant_options_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Уникальный UUID",
                    ),
                ),
                (
                    "iiko_uuid",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="UUID стола в iiko",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Номер стола")),
                (
                    "qr",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="QR-код",
                    ),
                ),
                (
                    "call_waiter",
                    models.BooleanField(default=False, verbose_name="Вызов официанта"),
                ),
                (
                    "call_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время вызова"
                    ),
                ),
                (
                    "bill_waiter",
                    models.BooleanField(default=False, verbose_name="Запрос счёта"),
                ),
                (
                    "bill_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время запроса счёта"
                    ),
                ),
                (
                    "iiko_waiter_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID официанта в iiko",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="restaurant.section",
                        verbose_name="Секция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол и его QR код",
                "verbose_name_plural": "Создание столов и QR кодов",
                "ordering": ["number"],
                "unique_together": {("section", "number")},
            },
        ),
    ]
