# Generated by Django 5.1.6 on 2025-04-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="closing_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время закрытия"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="opening_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время открытия"
            ),
        ),
    ]
