# Generated by Django 5.1.6 on 2025-04-25 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Тип меню"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип меню",
                "verbose_name_plural": "Типы меню",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, verbose_name="Название блюда (Русский)"
                    ),
                ),
                (
                    "name_kz",
                    models.CharField(
                        max_length=255, verbose_name="Название блюда (Казахский)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="menus/images/",
                        verbose_name="Изображение блюда",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание блюда (Русский)"
                    ),
                ),
                (
                    "description_kz",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание блюда (Казахский)"
                    ),
                ),
                (
                    "calories",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Укажите калорийность блюда в килокалориях",
                        null=True,
                        verbose_name="Калории (ккал)",
                    ),
                ),
                (
                    "proteins",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Укажите количество белков в граммах",
                        max_digits=5,
                        null=True,
                        verbose_name="Белки (г)",
                    ),
                ),
                (
                    "fats",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Укажите количество жиров в граммах",
                        max_digits=5,
                        null=True,
                        verbose_name="Жиры (г)",
                    ),
                ),
                (
                    "carbohydrates",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Укажите количество углеводов в граммах",
                        max_digits=5,
                        null=True,
                        verbose_name="Углеводы (г)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Укажите цену блюда в тенге",
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, если блюдо доступно для заказа",
                        verbose_name="Доступно?",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время обновления"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menus",
                        to="restaurant.restaurant",
                        verbose_name="Ресторан",
                    ),
                ),
                (
                    "menu_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menus",
                        to="products.menutype",
                        verbose_name="Тип меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
                "indexes": [
                    models.Index(
                        fields=["name_ru", "restaurant"],
                        name="products_me_name_ru_a1009d_idx",
                    ),
                    models.Index(
                        fields=["is_available"], name="products_me_is_avai_2255f0_idx"
                    ),
                ],
            },
        ),
    ]
